Task 1. Write a Python function that converts a temperature from Fahrenheit to Celsius. Use `numpy.vectorize` to apply this function to an array of temperatures: `[32, 68, 100, 212, 77]`.
   - Formula: $C = (F - 32) \times \frac{5}{9}$

---

Task 2. Create a custom function that takes two arguments: a number and a power. Use `numpy.vectorize` to calculate the power for each pair of numbers in two arrays: `[2, 3, 4, 5]` and `[1, 2, 3, 4]`.

---

Task 3. Solve the system of equations using `numpy`:

$$
\begin{cases}
4x + 5y + 6z = 7 \\
3x - y + z = 4 \\
2x + y - 2z = 5
\end{cases}
$$

---

Task 4. Given the electrical circuit equations below, solve for $I_1, I_2, I_3$ (currents in the branches):

$$
\begin{cases}
10I_1 - 2I_2 + 3I_3 = 12 \\
-2I_1 + 8I_2 - I_3 = -5 \\
3I_1 - I_2 + 6I_3 = 15
\end{cases}
$$

---


**Image Manipulation with NumPy and PIL**

Image file: `images/birds.jpg`. Your task is to perform the following image manipulations using the **NumPy** library while leveraging **PIL** for reading and saving the image.

**Instructions:**

1. **Flip the Image**:
   - Flip the image horizontally and vertically (left-to-right and up-to-down).

2. **Add Random Noise**:
   - Add random noise to the image.

3. **Brighten Channels**:
   - Increase the brightness of the channels (r.g. red channel) by a fixed value (e.g., 40). Clip the values to ensure they stay within the 0 to 255 range.

4. **Apply a Mask**:
   - Mask a rectangular region in the image (e.g., a 100x100 area in the center) by setting all pixel values in this region to black (0, 0, 0).

**Requirements:**
- Use the **PIL** module onyl to:
  - Read the image.
  - Convert numpy array to image.
  - Save the modified image back to a file.
- Perform all manipulations using NumPy functions. Avoid using image editing functions from PIL or other libraries.


**Bonus Challenge**:
- Create a function for each manipulation (e.g., `flip_image`, `add_noise`, `brighten_channels`, `apply_mask`) to promote modularity and reusability of code.

---

In [1]:
import numpy as np
from matplotlib.style.core import library


def converttocelcius(farenheit):
    return (farenheit - 32)*5/9
vecconvertion=np.vectorize(converttocelcius)
farenheit=[32,68,100,212,77]
print(vecconvertion(farenheit))

[  0.          20.          37.77777778 100.          25.        ]


In [2]:
def powers(a,b):
    return a**b

vecpower=np.vectorize(powers)
a=[2,3,4,5]
b=[1,2,3,4]
print(vecpower(a,b))

[  2   9  64 625]


In [11]:
array=np.array([[4,5,6],[3,-1,1],[2,1,-2]])
answer=np.array([7,4,5])
print(np.linalg.solve(array,answer))

[ 1.7027027   0.62162162 -0.48648649]
[ 1.7027027   0.62162162 -0.48648649]


In [6]:
matrix=np.array([[10,-2,3],[-2,8,-1],[3,-1,6]])
b=np.array([12,-5,15])
print(np.linalg.solve(matrix,b))

[ 0.48963731 -0.2253886   2.21761658]


In [24]:
import requests
from bs4 import BeautifulSoup as bs
with open('/Users/orifjonqarshiboyev/Downloads/Full CDI.html','r',encoding='utf-8') as f:
    content=f.read()
    soup=bs(content,'html.parser')
    soup.prettify()



<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@600&amp;display=swap" rel="stylesheet"/>
  <title>
   IELTS Reading Test - Save the Turtles
  </title>
  <style>
   /* All CSS styles remain exactly the same as in the original code */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #ffffff;
            line-height: 1.4;
            font-size: 16px;
        }

        .header {
            background-color: #ffffff;
            padding: 12px 20px;
            border-bottom: 1px solid #e0e0e0;
            display: flex;
            justify-content: space-between;
            align-items: center;
            position: fixed;
            top: 0;
            left: 0;
            right:

In [22]:
pip install lxml

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 2.7 MB/s  0:00:03 eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


SyntaxError: invalid syntax (1363284836.py, line 1)