In [2]:
import numpy as np

1. Create a vector with values ranging from 10 to 49.
2. Create a 3x3 matrix with values ranging from 0 to 8.
3. Create a 3x3 identity matrix.
4. Create a 3x3x3 array with random values.
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.
7. Normalize a 5x5 random matrix.
8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
9. Create two 3x3 matrices and compute their dot product.
10. Given a 4x4 matrix, find its transpose.
11. Create a 3x3 matrix and calculate its determinant.
12. Create two matrices \( A \) (3x4) and \( B \) (4x3), and compute the matrix product \( A \cdot B \).
13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.
14. Solve the linear system \( Ax = b \) where \( A \) is a 3x3 matrix, and \( b \) is a 3x1 column vector.
15. Given a 5x5 matrix, find the row-wise and column-wise sums.

In [3]:
vector = np.arange(10,49)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [5]:
vector=np.arange(0,9)
new=vector.reshape(3,3)
print(new)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
matrix=np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
array=np.random.rand(3,3,3)
print(array)


[[[0.08447801 0.85951268 0.41846942]
  [0.12890518 0.74512317 0.81393903]
  [0.20220798 0.68158156 0.92526534]]

 [[0.47214171 0.46996553 0.05125577]
  [0.86235729 0.91786683 0.82427446]
  [0.54211177 0.82642609 0.22234943]]

 [[0.02866137 0.24055815 0.91769449]
  [0.12613828 0.44798379 0.34372707]
  [0.95805625 0.83954724 0.72590497]]]


In [10]:
array=np.random.rand(10,10)
print(array)
print(array.max())
print(array.min())

[[0.19556246 0.56231132 0.58185575 0.68035903 0.95260705 0.14450555
  0.34776393 0.22286496 0.85131115 0.00674668]
 [0.31253548 0.28555732 0.46506256 0.29376935 0.23824849 0.78017572
  0.73892983 0.0210843  0.72964149 0.68942817]
 [0.07054578 0.20011401 0.11359161 0.23581757 0.74909113 0.78011367
  0.18075173 0.08951621 0.0954145  0.07830444]
 [0.73482273 0.64972715 0.6687095  0.44459447 0.21651836 0.48757115
  0.59210494 0.52618646 0.92247664 0.49045768]
 [0.72652569 0.19714489 0.12549923 0.59148854 0.59496628 0.0788833
  0.28618798 0.60562903 0.74254858 0.48582506]
 [0.20958969 0.21144363 0.0250327  0.53088111 0.53207673 0.44421368
  0.78816965 0.49775745 0.08426465 0.89550666]
 [0.42820587 0.1497102  0.72285371 0.45255374 0.13338834 0.58499071
  0.78265912 0.15034067 0.97308187 0.10524613]
 [0.87003908 0.33643742 0.07511407 0.91320725 0.39215301 0.81303186
  0.06217828 0.36888843 0.38363873 0.94691884]
 [0.39470299 0.20540765 0.21668187 0.2569183  0.28116253 0.79686528
  0.09765977 

In [12]:
vector = np.random.rand(30)
print(sum(vector)/len(vector))

0.5428454320636924


In [13]:
matrix = np.random.rand(5,5)




[[0.56027422 0.04203573 0.45463068 0.10661714 0.3655647 ]
 [0.29794724 0.91950046 0.86819493 0.80838367 1.        ]
 [0.13329689 0.         0.74855167 0.20409343 0.41496334]
 [0.72426197 0.89829149 0.40260687 0.07585577 0.49027468]
 [0.78274655 0.71562573 0.18701177 0.42462318 0.95504447]]


In [14]:
matrix1=np.random.rand(5,3)
matrix2=np.random.rand(3,2)
print(matrix1.dot(matrix2))

[[0.29063225 0.15373248]
 [0.46832356 0.18037481]
 [0.7226382  0.19975515]
 [0.43630228 0.24838891]
 [0.66291096 0.31790654]]
